[package]
name = "tigadb"
version = "0.1.0"
authors = ["CrocdileChan <CrocdileChan@github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.3"
mmap = "0.1.1"
parking_lot = "0.10.0"